services:
  api:
    container_name: livros-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5004:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: ["livros-api-sql"]
    networks:
      livros-networks:

  livros-api-sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=SenhaDbLivros01"
    volumes:
      - "livros-api-mssql-azure-edge:/var/opt/mssql"
    networks:
      livros-networks:
        aliases:
          - "sql"

volumes:
  livros-api-mssql-azure-edge:

networks:
  livros-networks:
    driver: bridge
